Module1 task2
htmlacademy-yii/806805-task-force-1 pull request #2
Opened 2019-10-31 05:54 UTC by allomir

Fate stone #1

2019-11-02 19:20 UTC, allomir commented
***
Новый файл ДЕСТВУЮЩИЙ _task_process.php
ОТМЕНЕННЫЙ файл task_process#1.php

2019-11-04 20:06 UTC, kostromich requested changes
Предлагаю уменьшить количество файлов в первом задании.
Нам потребуется всего один класс: Задание (Task), в котором будут определены
1) Несколько констант для статусов, массив со статусами (можно использовать статическое свойство).
2) То же самое для ролей.
3) То же самое для действий.
4) Возможные переходы между статусами в виде массива
```
id_статуса_1 => id_действия_1 => id_статуса_3
                      => id_действия_2 => id_статуса_4
```
5) Метод, который будет принимать id_действия и возвращать id нового статуса, с учётом исходного статуса присвоенного задаче

Пока не усложняй структуру всякими сущностями типа "Кнопка" и то, что будет написано на ней.

В конструкторе задачи на понадобятся следующие свойства: id_заказчика, id_исполнителя, id_статуса и дата дедлайна (необязательный параметр)

2019-11-09 18:37 UTC, allomir commented
- Удалена лишняя информация
- Добавлен массив переходов private static $status_changers
- Изменен Конструктор задачи 
- Добавлен методы показа статусов и действий
- Добавлен метод проверка Задание просрочено

2019-11-12 17:40 UTC, allomir commented
- Изм Название класса TaskProcess согласно PHP  прав именования PHP coding standards
- Добавлена свойство  static private $status_changers_rules - переходы в зависимости от роли
- Изм названия действий с act на action 
- Добавлено свойство static private $status_changers_by_facts - изменение статуса по событию, чтобы не путаться с кнопками-действиями
- изм метод для проверки статуса по событию check_is_end_life() Стало show_next_status_by_life() потому что мы не проверяем время а узнаем новый статус по событию
- исправлена ошибка в методах, происходит обращение к массиву с несуществующим ключом

2019-11-13 09:46 UTC, allomir commented
- Изм показать следующий статус, учтена роль пользователя (проверка разрешенные действия)
$is_right_actions;
- Условно принято что просматривает задание либо  Заказчик либо Исполнитель, в дальнейшем необходимо определять что любой Исполнитель может делать предложение
- изм конструктор - в нем определяется кто просматривает - id Исполнитель или Заказчик 
- исп ошибка array_serch - ключ 0 дает ошибку в условиях, поэтому проверяем что число

2019-11-14 15:25 UTC, allomir commented
- просто и гениально, убрал лишнее
- только camelCase. Имя класса Task
- Добавлены новые действия
ACTION_SET_CONTRACTOR - Выбрать исполнителя.
ACTION_ACCEPT - принять те согласится после того как выбрали исполнителя (раньше думал что это выбрать исполнителя), также принять работает совместно с ACTION_FAILUREL (отказаться) - те у Исполнителя есть выбор Принять или Отказаться после того как его выбрали.
ACTION_ADD_TASK - Добавить задание.
- Тест супер
- спасибо Martin

2019-11-14 15:32 UTC, merged